<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
$(document).ready(function(){$("#flickr-submit").click(function(c){function l(c){var l='<ul class="photos">';$.each(c.items,function(c,a){l+='<li class="pics">',l+='<a href="'+a.link+'" class="thumbnails">',l+='<img src="'+a.media.m+'"></a></li>'}),l+="</ul>",$(".gallery").html(l)}c.preventDefault();var a="http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?",i=$("#flickr-search").val(),s={tags:i,format:"json"};$.getJSON(a,s,l)})});
=======
$(document).ready(function(){var e=[];$("#flickr-submit").click(function(a){function t(a){function t(){$.each(e,function(a,t){var i=t.href;$.getJSON(i).done(function(t){e[a].details=t})})}$.each(a.albums.items,function(a,t){if(t.images.length>0){var i={id:t.id,name:t.name,href:t.href,image:t.images[0].url};e.push(i)}}),t(),console.log(a);var i="";$.each(e,function(e,a){i+='<div class="photos">',i+='<img src="'+a.image+'"></div>'}),i+="</div>",$(".gallery").html(i)}a.preventDefault();var i="https://api.spotify.com/v1/search",o=$("#flickr-search").val().toLowerCase(),r={q:o,type:"album"};console.log(e),$.getJSON(i,r,t)}),$(".gallery").on("click","img",function(){var e=$(this).attr("src"),a=$(this).attr("data-href");$(".overlay-poster").attr("src",e),$("#overlay").addClass("open")}),$("#overlay").click(function(){$("#overlay").removeClass("open")})});
>>>>>>> spotify-test
=======
$(document).ready(function(){var e=[];$("#flickr-submit").click(function(a){function t(a){function t(){$.each(e,function(a,t){var i=t.href;$.getJSON(i).done(function(t){e[a].details=t})})}$.each(a.albums.items,function(a,t){if(t.images.length>0){var i={id:t.id,name:t.name,href:t.href,image:t.images[0].url};e.push(i)}}),t(),console.log(a);var i="";$.each(e,function(e,a){i+='<div class="photos">',i+='<img src="'+a.image+'"></div>'}),i+="</div>",$(".gallery").html(i)}a.preventDefault();var i="https://api.spotify.com/v1/search",o=$("#flickr-search").val().toLowerCase(),r={q:o,type:"album"};console.log(e),$.getJSON(i,r,t)}),$(".gallery").on("click","img",function(){var e=$(this).attr("src"),a=$(this).attr("data-href");$(".overlay-poster").attr("src",e),$("#overlay").addClass("open")}),$("#overlay").click(function(){$("#overlay").removeClass("open")})});
>>>>>>> spotify-test
=======
$(document).ready(function(){var e=[],a=20;$("#flickr-submit").click(function(t){function s(t){function s(e){console.log(e)}$.each(t.albums.items,function(a,t){function s(){$.each(e,function(a,t){var s=t.href;$.getJSON(s).done(function(t){e[a].details=t})})}if(t.images.length>0){var n={id:t.id,name:t.name,href:t.href,image:t.images[0].url};e.push(n)}s()});var n="https://search.twitter.com/search.json?",l=$("#flickr-search").val().toLowerCase(),i={q:l,type:"json",limit:a};$.getJSON(n,i,s);var r="";$.each(e,function(e,a){r+='<div class="photos">',r+='<img src="'+a.image+'" alt=" '+a.name+' ">',r+="</div>"}),$(".gallery").html(r)}t.preventDefault();var n="https://api.spotify.com/v1/search",l=$("#flickr-search").val().toLowerCase(),i={q:l,type:"album",limit:a};console.log(e),$.getJSON(n,i,s)}),$(".gallery").on("click","div",function(){var a=$(this).index(),t=[];$.each(e,function(e,a){var s={index:e,name_album:a.name,name_band:a.details.artists[0].name,release_date:a.details.release_date,tracks_arr:a.details.tracks,poster:a.details.images[0].url};t.push(s)}),$(".artist").html("<span>Artist :</span> "+t[a].name_band),$(".album").html("<span>album :</span> "+t[a].name_album),$(".release").html("<span>Release Date :</span> "+t[a].release_date),console.log(t);var s=t[a].poster;$(".overlay-poster").attr("src",s),$("#overlay").addClass("open").css("display","flex")}),$("#overlay").click(function(){$("#overlay").removeClass("open")})});
>>>>>>> spotify-test
